version: "3"

services: 
  app:
    container_name: hetic-library_app
    build:
      context: .
      dockerfile: .docker/app/dev.Dockerfile
    volumes:
        - "./app:/app"
    ports:
      - 80:8080
    networks: 
      - elastic
  elasticsearch: 
    container_name: hetic-library_elasticsearch
    image: elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana: 
    container_name: hetic-library_kibana
    image: kibana:7.13.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge