version: "3"

services: 
  app:
    container_name: hetic-library_app
    build:
      context: .
      dockerfile: .docker/app/dev.Dockerfile
    volumes:
        - "./app:/app"
    ports:
      - 80:8080
  


